name: Build and Puch Docker Image

on:
  push:
    branches:
        - main

env:
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    REPO_NAME: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to  Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get short SHA using action
      id: short_sha_action
      uses: benjlevesque/short-sha@v1.2.0 #


    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:${{ steps.short_sha_action.outputs.sha }}
        file: ./Dockerfile